name: Lucas
favicon: null
layout_spectrum: 0.800513552268967
typography_spectrum: 0.8386846161447465
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#E0FBFC'
    - '#C2DFE3'
    - '#9DB4C0'
    - '#5C6B73'
    - '#253237'
  brandStrength: 0.4974259599111974
  lightness: 0.6126206079497933
  saturation: 0.35872437502257526
  rhythmicContrast: 0.04077075305394828
purpose: []
